### ISSUE TITLE
Validation architecture

### ISSUE THREAD

**Issue by makeworld-the-better-one** [starlinglab/integrity-backend#103]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Detach verification from any specific repo and abstract different kinds of verification as much as possible

### Validation methods
- Proofmode (gpg)
- sig66 (starlinglab/organizing-private#66)
- Starling Capture: openssl, zion, zion-session
- Local WACZ: ecdsa - https://github.com/webrecorder/specs/blob/main/wacz-auth/spec.md
- Server crawl WACZ: TLS cert - use authsign lib

### Delivery methods
- HTTP with JWT
- Dropbox
- Signal
- Trusted manual input
- SD card

## To Do
- [x] Rename verification to validation
- [x] Create separate module for all verification methods
	- [x] Move #102 there
	- [x] Class for each verifier with `name()`, `validate()`
	- [x] Also `validated_sigs_json()` or something that returns C2PA-style JSON that can be put in the metadata
		- [x] with pretty mode that truncates fields to 100 chars
- [x] Move HTTP input in integrity-backend into a separate repo - it's now a preprocessor
	- Take JWT, parse content, put everything into metadata, create zip, put into input
	- Standardize JWT format
- [x] Integrate verifier module into all the preprocessors
	- [x] proofmode signal
	- [x] Server WACZ
	- [x] Starling Capture over HTTP
- [x] Clean up integrity-backend - https://github.com/starlinglab/integrity-backend/pull/108
	- [x] Remove http server (handlers, multipart, readme, Pipfile, main.py, etc)
	- [x] Comment out c2pa-starling-capture to be fixed later in another PR (see [this commit](https://github.com/starlinglab/integrity-backend/pull/104/commits/a2bb17b22d7b84209c1a9177c9f52a8f719d82fd))
	- [x] Add back HTTP docs to preprocessor
- [x] Docs on validation methods and their JSON output in preprocessor README

![20220526_102124](https://user-images.githubusercontent.com/25111343/170511156-65f8ec88-ea06-4290-b4ed-f0a879b52e31.jpg)

**Comment by makeworld-the-better-one** [comment]
In progress on verify branch: https://github.com/starlinglab/integrity-preprocessor/tree/verify

**Comment by makeworld-the-better-one** [comment]
## Pull Requests for this issue
- https://github.com/starlinglab/integrity-preprocessor/pull/25
- https://github.com/starlinglab/integrity-backend/pull/108
