### ISSUE TITLE
Upgrade to new C2PA

### ISSUE THREAD

**Issue by makeworld-the-better-one** [starlinglab/integrity-backend#111]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** See below  

Adobe has released their C2PA software to the public, and the C2PA spec has changed. We must update our software to match the open source tooling, and so that software using the new spec (like Photoshop) can work with our pipeline.

## To Do

- [x] Update code to use new claim tool - https://github.com/contentauth/c2patool
	- Rename module
- [x] Update JSON in integrity-backend and JSON-generating code
- [x] Update integrity-schema to match new C2PA spec
- ~~[ ] Keep old schema, and map it to the C2PA spec version it was for (rename folder)~~
- [x] Have table like this:
```
claim tool version | c2pa spec version | verifier website
```
- Verifier website is https://verify-beta.contentauthenticity.org/inspect (old) or https://verify-alpha.contentauthenticity.org/inspect (super old) or https://verify.contentauthenticity.org/inspect (new)
   
- [x] Fix Exif generation in code, see below
- [x] Tests for new Exif code
- [x] Update Exif data in integrity-schema
- [x] Handle cert in code

**Comment by makeworld-the-better-one** [comment]
## PRs
- https://github.com/starlinglab/integrity-schema/pull/9
- https://github.com/starlinglab/integrity-backend/pull/112

**Comment by makeworld-the-better-one** [comment]
## Fix Exif data

The `stds.exif` data generated by this repo is wrong. It needs to follow the [XMP Exif spec](https://github.com/adobe/xmp-docs/blob/master/XMPNamespaces/exif.md). There is an example [here](https://c2pa.org/specifications/specifications/1.0/specs/C2PA_Specification.html#_exif_information) from the C2PA spec. Copied below:

```json
{
  "@context" : {
    "dc": "http://purl.org/dc/elements/1.1/",
    "exifEX": "http://cipa.jp/exif/2.32/",
    "exif": "http://ns.adobe.com/exif/1.0/",
    "tiff": "http://ns.adobe.com/tiff/1.0/",
    "xmp": "http://ns.adobe.com/xap/1.0/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  },
  "exif:GPSVersionID": "2.2.0.0",
  "exif:GPSLatitude": "39,21.102N",
  "exif:GPSLongitude": "74,26.5737W",
  "exif:GPSAltitudeRef": 0,
  "exif:GPSAltitude": "100963/29890",
  "exif:GPSTimeStamp": "2019-09-22T18:22:57Z",
  "exif:GPSSpeedRef": "K",
  "exif:GPSSpeed": "4009/161323",
  "exif:GPSImgDirectionRef": "T",
  "exif:GPSImgDirection": "296140/911",
  "exif:GPSDestBearingRef": "T",
  "exif:GPSDestBearing": "296140/911",
  "exif:GPSHPositioningError": "13244/2207",
  "exif:ExposureTime": "1/100",
  "exif:FNumber": 4.0,
  "exif:ColorSpace": 1,
  "exif:DigitalZoomRatio": 2.0,
  "tiff:Make": "CameraCompany",
  "tiff:Model": "Shooter S1",
  "exifEX:LensMake": "CameraCompany",
  "exifEX:LensModel": "17.0-35.0 mm",
  "exifEX:LensSpecification": { "@set": [ 1.55, 4.2, 1.6, 2.4 ] }
}
```

cc @benhylau

**Comment by benhylau** [comment]
- Buy signing certificate and handle in code
- Resolve GPS format in EXIF

**Comment by YurkoWasHere** [comment]
Generate Self-Signed Certificate for document signing:

```
# Create CA
openssl genrsa -out cacert.key 2048
openssl req -new -x509 -days 365 -key cacert.key -out cacert.crt
touch index.txt
echo 1000 > serial

# Generate Private Key, Signing Request
openssl genrsa -out document.key 2048
openssl req -utf8 -nameopt oneline,utf8 -new -key document.key -out document.csr

# Sign the request
openssl x509 -days 365 -CA cacert.crt -CAkey cacert.key -CAserial serial -in document.csr -req -out document.crt

# Export as p12 (for testing in adobe acrobat)
openssl pkcs12 -export -in document.crt -inkey document.key -out document.p12
```

**Comment by makeworld-the-better-one** [comment]
> @makeworld-the-better-one did we ever resolve the EXIF GPS format issue? I am guessing this new method `_convert_coords_to_c2pa` is the correct transformation?

@benhylau yes, in #112 all the GPS information should be in the correct valid C2PA format. And yes, `_convert_coords_to_c2pa` is the bulk of the change.

**Comment by makeworld-the-better-one** [comment]
PRs merged
