### ISSUE TITLE
Migration for C2PA legacy code

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#120]
## Task Summary

📅 **Due date:** end-Oct  
🎯 **Success criteria:** Get the code that works in lab2 working in mainline.  

See: https://github.com/starlinglab/integrity-backend/blob/main/integritybackend/actions.py

## To Do

- [x] Agree on schema from preproc
- [x] Read data from `-meta-content.json`
- [x] Add GPS keys to top level schema for location
  - Note that if GPS and location need to be private, preproc should put them into `private` and not the public fields

**Comment by benhylau** [comment]
- Fix `c2pa_starling_capture`
  - re-enable it
  - read GPS from `-meta-content.json`
  - go over to http pre-proc and make sure GPS is put into `-meta-content.json` under `private`
- Remove `c2pa_add` `c2pa_update` `c2pa_store` `c2pa_custom`

**Comment by YurkoWasHere** [comment]
Startling "legacy" Capture
https://github.com/starlinglab/integrity-preprocessor/blob/integrity-legacy/folder/main.py#L251-L273

**Comment by makeworld-the-better-one** [comment]
## PRs
- https://github.com/starlinglab/integrity-schema/pull/13

(Will be updated)

**Comment by makeworld-the-better-one** [comment]
> - [ ]  @YurkoWasHere to update "folder pre-processor"

The folder pre-processor deals with WACZs and proofmode, so I don't think there is anything to do there. Proofmode doesn't have geolocation data added to meta-content as decided earlier.

All steps for this issue should now be completed, waiting on PR review and testing before closing.
