### ISSUE TITLE
Add smoke testing for API server

### ISSUE THREAD

**Issue by anaulin** [starlinglab/integrity-backend#23]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** We are confident at all times that code in `main` can successfully serve basic `/create` requests

Right now the only automated tests we have are a couple of unit tests for the logic behind claim generation. It would be good to have a way to automatically verify that code at head is still functional enough that it can serve basic API requests. Ideally we would run such a test in CI before merging.

## To Do

- [ ] Write script that can send the server a basic request
- [ ] (maybe) Add assets and configuration so that server can be automatically tested with this script (i.e. vendorize `claim_tool`, add an image to test with, etc)
- [ ] (maybe) Add running this script as a step to CI and/or deploys

**Comment by benhylau** [comment]
I think we are still waiting on clarity on what API is needed.

**Comment by benhylau** [comment]
@makeworld-the-better-one this can be the ticket that tracks the test cases for the API work for this quarter. Feel free to add this to existing ticket or track here.

**Comment by makeworld-the-better-one** [comment]
These tests have been lumped in with https://github.com/starlinglab/integrity-preprocessor/pull/25 as that's where the http server is now.

Tests written:
- [x] No JWT
- [x] Good POST
- [ ] Missing signature
- [ ] Non-image?
- [ ] ???

**Comment by makeworld-the-better-one** [comment]
Closing as PR with testing has been merged.
