### ISSUE TITLE
Specific input data and claim formats

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#3]
## Task Summary

📅 **Due date:** 24 Nov 2021  
🎯 **Success criteria:** Specify data formats and schema of the Starling Capture API.  

## To Do

- [x] Specify current output of Starling Capture
- Specify claim format for input into `claim-tool` at:
  - [x] Capture assertion (post Starling Capture app)
  - [x] Edit assertion (post Nexus/Photoshop)
  - [x] Store assertion (post IPFS/Filecoin)
- [x] Detail transformations necessary at each stage
- [ ] Document in more permanent place

**Comment by benhylau** [comment]
The last subtask here seems to be same as #9.
