### ISSUE TITLE
Integrate ISCN registration into integrity API server

### ISSUE THREAD

**Issue by anaulin** [starlinglab/integrity-backend#53]
## Task Summary

📅 **Due date:** mid-March  
🎯 **Success criteria:** When an asset is pushed by our server to IPFS, it also registers the piece of content on ISCN (at least one one chain)

- [Example registered content](https://app.like.co/view/iscn:%2F%2Flikecoin-chain%2Flaa5PLHfQO2eIfiPB2-ZnFLQrmSXOgL-NvoxyBTXHvY%2F1)
- [ISCN Tx sample](https://github.com/likecoin/iscn-specs/blob/master/sample/iscn-tx-sample-1.json#L22-L33)

## To Do

- [x] investigate LikeCoin libraries, understand at a high level what they do: https://github.com/likecoin/iscn-batch-uploader, https://github.com/likecoin/iscn-js
- [x] decide best way to integrate this into our Python3-based server (do we call out to a Node executable? into a separate Node-based service running locally? something else?)
- [x] implement integration in code
- [x] set up wallet to be held by the server to fund the registration, get wallet funded
- [x] decide on schema for registration for our specific use cases(s)
- [ ] implement registration schema in code
- [x] verify registrations appear as intended on-chain

**Comment by anaulin** [comment]
Misc notes and bookmarks for my own future reference:
* https://github.com/likecoin/iscn-js lib seems a relatively straightforward implementation of a series of signing and transaction broadcast steps, depending largely on the  `@cosmjs/stargate` libraries. Which is to say: we could probably implement our own purpose-specific implementation of this using either directly the Cosmos SDKs or even talking directly to Cosmos APIs
* Re: Cosmos APIs, really it seems like `POST /txs` is the main API we'd need, and there is a non-deprecated REST version of it: https://v1.cosmos.network/rpc/v0.41.4 (unless this entire API is deprecated, I'm struggling a bit to understand the layout of Cosmos' API docs)
* Seems like LikeCoin themselves have a REST API for making an ISCN registration: https://api.docs.like.co/#3312f20a-92f9-4af9-a492-c0f243304d60 it requires logging in via OAuth into an "account", and using your OAuth token for the API requests, but that is something that the server could manage.

**Comment by benhylau** [comment]
>Seems like LikeCoin themselves have a REST API for making an ISCN registration: https://api.docs.like.co/#3312f20a-92f9-4af9-a492-c0f243304d60 it requires logging in via OAuth into an "account", and using your OAuth token for the API requests, but that is something that the server could manage.

I wonder if this is the custodial wallet flow where LikeCoin manages a wallet on your behalf, and issues you an oauth token.  The wallet flow shouldn't have a Liker ID. Not sure.

>This is possibly a workable foundation for communicating with Cosmos directly from Python: https://github.com/hukkin/cosmospy (helps with singing, and then you can just post the signature to Cosmos)

I recall William said something about JS being the more developed libraries in Cosmos. My concern with this path is we end up being maintainer of a iscn-python library that needs to track a changing ISCN spec. However, I see how this can be just a small file that suits our specific needs.

Let's ask what William thinks about this path?

**Comment by anaulin** [comment]
Yep, I believe the OAuth flow is where you have a LikerID that's linked to your wallet, and then you use OAuth to identify yourself as the owner of that LikerID.

**Comment by anaulin** [comment]
@benhylau I need help figuring out what do we want to put in the ISCN registration.

The schema definition is here: https://github.com/likecoin/iscn-specs/tree/master/schema

It seems the most important part of this is the "contentMetadata" section:
```
  "contentMetadata": {
    "@context": "http://schema.org/",
    "@type": "Article",
    "name": "使用矩陣計算遞歸關係式",
    "description": "An article on computing recursive function with matrix multiplication.",
    "datePublished": "2019-04-19",
    "version": 1,
    "url": "https://nnkken.github.io/post/recursive-relation/",
    "author": "https://github.com/nnkken",
    "usageInfo": "https://creativecommons.org/licenses/by/4.0",
    "keywords": "matrix,recursion"
  }
```

William's server only makes the "type" required. There are other fields outside of this contentMetadata section (e.g. stakeholders) which we might or might not want to use.

We are going to be doing this registration right after we upload the file to FileCoin. At that point we have the `ipfs_cid` and the `organization_id`. Based on the `organization_id` we can get the `creative_work_author` configuration from our `config.json`, or any other organization-specific configuration that we put there.

My questions for you:
* Is it correct to use the CID as `ipfs://{ipfs_cid}` in the "fingerprints" section of the registration? Or does this fingerprint need to be derived differently?
* Do we want to put anything in the "stakeholders" section? If so, what?
* Is it ok to use `CreativeWork` for "type" for all of our registrations?
* What other fields do we want to fill in, and how?

**Comment by benhylau** [comment]
@benhylau to sort this and reviewed with LikeCoin before @anaulin comes back from vacation. New APIs?

We have the org id but not the full JWT.

**Comment by anaulin** [comment]
From a conversation with William, it seems like it is strongly recommended that we provide at least the fields: `name`, `description`, `type`, `contentFingerprints` (at least one fingerprint).

For `type` we would use a subclass of `CreativeWork` (https://schema.org/CreativeWork#subtypes), e.g. `Image`, `Video`, `Text`, etc. And we can provide any additional metadata we want that is suitable for that CreativeWork type schema (e.g. `exif` data for an `Image`).

Here is an example from William of a record with extra data for a sub-type of Creative Work https://app.like.co/view/iscn:%2F%2Flikecoin-chain%2Flaa5PLHfQO2eIfiPB2-ZnFLQrmSXOgL-NvoxyBTXHvY%2F1 (you can click on "View Raw Data" to see the actual JSON structure).

@benhylau for us I think the hard part is going to be figuring out what the types and descriptions and names need to be.

**Comment by benhylau** [comment]
>Is it correct to use the CID as ipfs://{ipfs_cid} in the "fingerprints" section of the registration? Or does this fingerprint need to be derived differently?

Let's do SHA256 and CIDv1:
- https://www.w3.org/TR/did-core/#bib-multibase
- https://proto.school/anatomy-of-a-cid/05

We'll have a helper func to compute each, so for now just mock a helper function for either.

>Do we want to put anything in the "stakeholders" section? If so, what?

Leave empty. I read the docs and feel it is not useful for out purpose at least for now.

>Is it ok to use CreativeWork for "type" for all of our registrations?

For the UA stuff we can either use [ArchiveComponent](https://schema.org/ArchiveComponent) subtype or [CreativeWork](https://schema.org/CreativeWork). The subtype is more descriptive but I think may be overly specific to our system, and they seem mostly used for physical archives. Let's stick with CreativeWork.

>What other fields do we want to fill in, and how?

TBD

**Comment by anaulin** [comment]
Got it. All of this makes sense, thanks for the detailed responses, @benhylau.

I have followed up with William to clarify the `author` schema question, will let you know what he says. If we can't use exactly what we have in `config.json` for the `author`, we can compute a one-string version of it (e.g. we could set `author` to `${name} (${identifier})`, with `name` and `identifier` coming from the `creative_work_author` for the `organization_id` in our configuration).

**Comment by anaulin** [comment]
By the way, looking at https://schema.org/author, it seems like it is not meant to be an array, but just a single Person or Organization, and in our config.json  we set it to an array (which is what goes into the C2PA claims). So I think the way we have it set up right now I think might not be aligned with what [schema.org](http://schema.org/) expects.

Here is the example they give:
```json
{
        "@context": "https://schema.org",
        "@type": "BookSeries",
        "name": "The Hitchhiker's Guide to the Galaxy",
        "genre": "comedy science fiction",
        "startDate": "1979-10-12",
        "endDate": "1992-10-12",
        "abstract": "Earthman Arthur Dent is saved by his friend, Ford Prefect—an alien researcher for the titular Hitchhiker's Guide to the Galaxy, which provides info on every planet in the galaxy—from the Earth just before it is destroyed by the alien Vogons.",
        "author": {
            "@type": "Person",
            "givenName": "Douglas",
            "familyName": "Adams",
            "additionalName": "Noel",
            "birthDate": "1952-03-11",
            "birthPlace": {
                "@type": "Place",
                "address": "Cambridge, Cambridgeshire, England"
            },
            "deathDate": "2001-05-11",
            "deathPlace": {
                "@type": "Place",
                "address": "Highgate Cemetery, London, England"
            }
        }
    }
```

**Comment by anaulin** [comment]
One remaining question I have is: from where will we be calling this “registration”? Knowing the rough place in the data flow when we’ll be doing this helps me figure out what makes sense as parameters that can be passed, the interface between the various pieces of code, etc.

In my WIP PR I wired the registration into the implementation of the store “action”, just after uploading to Filecoin (see the diff for actions.py in https://github.com/starlinglab/starling-integrity-api/pull/58/files). Is this still correct?

If not, do we have a writeup / summary somewhere where I can peruse the intended data flow (is that Mural?) to figure this out? @benhylau

**Comment by anaulin** [comment]
William just confirmed that we can use an `Organization` or `Person`, and that they use just a string in the examples to keep it simple.

**Comment by benhylau** [comment]
## re: `author` schema

According to this it seems to take object or https://github.com/likecoin/iscn-specs/tree/master/schema/contentMetadata so that's consistent with what William has. What I am not sure is if it can take an array.

C2PA seems to allow for an array (from something we injected):
```
        {
          "label": "stds.schema-org.CreativeWork",
          "data": {
            "author": [
              {
                "identifier": "https://starlinglab.org",
                "name": "Benedict Lau"
              }
            ]
          }
        }
```

An earlier example from Adobe:

```
        {
          "label": "stds.schema-org.CreativeWork",
          "data": {
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "author": [
              {
                "@type": "Person",
                "credential": [
                  {
                    "url": "did:adobe:f78db44b3d758bbf1ac2b1da23d6a9bc8d4554bbc7ca6f78f5536d6cf813d218e?service=VerifiableCredentials"
                  }
                ],
                "identifier": "https://cai-identity.adobe.io/identities/did:adobe:f78db44b3d758bbf1ac2b1da23d6a9bc8d4554bbc7ca6f78f5536d6cf813d218e?service=VerifiableCredentials",
                "name": "Gavin Peacock"
              },
              {
                "@id": "https://www.twitter.com/gvnpeacock",
                "@type": "Person",
                "identifier": "https://cai-identity.adobe.io/identities/did:adobe:f78db44b3d758bbf1ac2b1da23d6a9bc8d4554bbc7ca6f78f5536d6cf813d218e?service=VerifiableCredentials",
                "name": "gvnpeacock"
              }
            ]
          }
        }
```

But just bc they are in examples, and not flagged in a verifier, doesn't mean they are "to-spec" 🥲

**Comment by benhylau** [comment]
>One remaining question I have is: from where will we be calling this “registration”?

The "place" is here:

<img width="1242" alt="Screen Shot 2022-03-03 at 6 21 23 PM" src="https://user-images.githubusercontent.com/2261308/156669706-5abbedc5-b575-4d86-b1fd-f607c23ba407.png">

🤔 but where is the code??

My thoughts on this aren't well formed yet. Still trying to make our "folder drop off" model from SCMP work with this new "batching" model. So treat this as a hypothetical flow and lmk what you think...

1. Content comes in through an Ingestor, gets stored in `org:collection:date` in the **internal** directory. Note that currently we do this:

Note that currently, this is how we store stuff...



3.

**Comment by anaulin** [comment]
### re: author schema

I ran the examples we have trough https://validator.schema.org/. My conclusions:
* having an array is actually fine and supported
* the `credential` property seems to be made up, and is not supported; the validator says "The property credentials is not recognized by the schema (e.g. schema.org) for an object of type Person."
  *  neither https://schema.org/Person nor https://schema.org/Organization have a `credential` property; but they do have a `hasCredential` property, which can be either a string or an object of type https://schema.org/EducationalOccupationalCredential
  
So this example is fully valid, according to this validator:
```
{
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "author": [
              {
                "@type": "Person",
                "identifier": "https://cai-identity.adobe.io/identities/did:adobe:f78db44b3d758bbf1ac2b1da23d6a9bc8d4554bbc7ca6f78f5536d6cf813d218e?service=VerifiableCredentials",
                "name": "Gavin Peacock"
              },
              {
                "@id": "https://www.twitter.com/gvnpeacock",
                "@type": "Person",
                "identifier": "https://cai-identity.adobe.io/identities/did:adobe:f78db44b3d758bbf1ac2b1da23d6a9bc8d4554bbc7ca6f78f5536d6cf813d218e?service=VerifiableCredentials",
                "name": "gvnpeacock"
              }
            ]
          }
}
```

**Comment by anaulin** [comment]
### re: general architecture and interface for our ISCN code

That all makes sense to me. It does sounds like we are moving the implementation of assembling the full registration JSON until we have the batching code ready, but that also seems straightforward to implement, since you've already thought through the various bits of e.g. how the organization is encoded.

I'm going to make a reviewable and mergeable version of the ISCN library, with documentation and such, which for now will be just a wrapper around the HTTP server call. Then I can move onto https://github.com/starlinglab/starling-integrity-api/issues/62, which seems also related to ISCN.

**Comment by benhylau** [comment]
@anaulin oh thanks for passing this thru the validator. The `credential` or `credentials` field is exactly the one I discussed with Adobe about. It seems to have some definition that is defined in C2PA: https://c2pa.org/public-draft/C2PA_Specification.html#_common_data_model_actor

<img width="742" alt="Screen Shot 2022-03-07 at 2 43 29 PM" src="https://user-images.githubusercontent.com/2261308/157106689-6e1af891-f6b2-4e14-a8cd-4a8cc794322d.png">

Their [verifier](https://verify.contentauthenticity.org) won't render the author unless there is a `credential` field, that is why I included a blank credential array.

<img width="728" alt="Screen Shot 2022-03-07 at 2 46 05 PM" src="https://user-images.githubusercontent.com/2261308/157106734-9d46105f-d59a-4ec5-bb2e-3019eef40718.png">

I think regardless of what we do with C2PA, we have to omit that field from our general schema as conforming endpoints (e.g. ISCN) will not like that. I can reach out to Adobe on what to do on C2PA side.

**Comment by anaulin** [comment]
Re: the extraneous `credential` field, we decided to remove it from our `config.json`, to make it compliant with schema.org, and instead we can have a line of code in our c2pa generation to add always a blank `credential: []` field (which is only necessary to appease the Adobe validator, for now).

@benhylau does it make sense to open a separate GitHub issue of this ^ bit?

**Comment by benhylau** [comment]
Done
