### ISSUE TITLE
Multi-org support of same instance

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#54]
## Task Summary

📅 **Due date:** Target Feb 16 ideally, otherwise Feb 23 (Phase 1)  
🎯 **Success criteria:** Add multi-org support and deploy on second instance (aka. BCN instance).  

Right now, each instance supports only one org because there is "org id" type of indicator in the API (or JWT) and the directory structure essentially assumes one org user per API. As a result, we have to deploy a Droplet per fellowship.

We can go two paths:
1. Dockerization
2. Insert an "org id" indicator in the HTTP message (probably JWT)

Here is a proposal for (2), which I think is the easier path:

In [the JWT](https://github.com/starlinglab/starling-integrity-api/blob/main/jwt-payload.json.example) add an `organization`, which can be `hyphacoop` for example. Then on the server, we need to change the following...

### 1. `INTERNAL_ASSET_STORE` directory

Currently we have `[ assets, claims, create, tmp ]` inside `internal`. Put these into an `organization` folder.

If the `organization` key is missing, we should fail the request. I considered a "default" for legacy JWTs but perhaps it's better that we phase out old JWTs.

### 2. `SHARED_FILE_SYSTEM` directory

Currently we have folders that are synced to a client FTP. We need to potentially sync each "org id" to a different FTP.

Can we find a tool that bi-directionally syncs each `organization` subdirectory over a separate FTP, each with its own credentials? Currently we are running a separate process, which is non-ideal.

### 3. Searches

Ensure that when searching for assets, each org searches only within its internal `organization` folder, under `INTERNAL_ASSET_STORE/organization/*`.

### 4. Org-specific hardcodes -> config file

These [hardcodes](https://github.com/starlinglab/starling-integrity-api/blob/main/starlingcaptureapi/claim.py#L37-L51) need to move to a JSON config file. FTP credentials should probably go in same file, and the "FTP sync tool" needs to somehow read from this. The schema for this config file needs to be defined.

## To Do

- [x] Decide if dockerization or "pathing" is the way to go _(edit: we're "pathing")_
- [x] Implement the code
- [ ] Add more storage on Droplet
- [ ] Deploy to "BCN instance" and perform data migration alongside #52 (both needs migrate, let's migrate once)
- [x] Mint new JWTs for BCN @benhylau 
- [x] Mint JWTs for 2nd org on the server (those phones will be with @lee94josh and @sophiamjones)

**Comment by YurkoWasHere** [comment]
`FTP` Sync
- We could have potentially a different sync platform per org. 
- Would most likely be triggered by cron job as you have no trigger of when remote file changes
- Could integrate SFTP sync script to check each org's json file and execute all syncs (1 per org) that are required
- makes most sense to put cred in json file
- Currently credentials need to be stored in `~/.netrc` this file would need to be updated from the json file before each pass
 
Things to watch out for
- watchdog of folders 
  - currently watching root folder
  - parse path for org id

**Comment by benhylau** [comment]
Figure out how to watch folders for multiple tenants https://github.com/starlinglab/starling-integrity-api/blob/31b037f1bfe0e40e5777205bd67e852168e395ed/starlingcaptureapi/fs_watcher.py#L35-L54

**Comment by benhylau** [comment]
This is done.
