### ISSUE TITLE
Integrate Numbers Protocol registration into integrity API server

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#56]
## Task Summary

📅 **Due date:** March 7, 2022  
🎯 **Success criteria:** Register to Numbers Protocol following same pattern as #53.   

Post-editorial content (same ones we register to LikeCoin ISCN) will be registered with Numbers. This will be similar to our integration with LikeCoin (https://github.com/starlinglab/starling-integrity-api/issues/53). In this case we'd have a IOTA wallet, register a CID, that'll allow future iterations of the asset be linked to it. This allows us to aggregate versions (and in the future, attestations) of an asset on IOTA.

_Note that the registration chain may change in the near term._

## To Do

- [x] See how we are doing #53 in https://github.com/starlinglab/starling-integrity-api/pull/58/files
- [x] Manually, ~~from Python~~ with curl, register a piece of data and verify entry on blockchain
- [x] Make a comment on the key materials necessary
  - Are we using a Starling wallet or Numbers has a wallet they use to register everyone behind the scenes? formerly is generally preferred but latter is acceptable as well, this usually changes whether we are making an API call to a public API or having to run wallet-blockchain coordination code locally. Sort this with Numbers.
- [x] Let @benhylau know what data fields are necessary
- [x] Integrate the registration code into repo according to flow diagram we discussed

**Comment by benhylau** [comment]
Numbers Protocol uses a CID as key to associate entries on AVAX. See (legacy, on IOTA) examples here: 

https://explorer.iota.org/mainnet/indexed/6261667962656961376275796c7a7533376c64747567716c32657570793634667733677a6a71796f69766774336a79786536643479756767683234

First we'll register an asset with a _Registration Record_ at creation. Bottom-most here:

![Screen Shot 2022-03-01 at 9 43 23 AM](https://user-images.githubusercontent.com/2261308/156189879-2060a585-1d26-4c5b-b7b4-2d0899388c73.png)

We'll use _Indexed Messages_ like [this one](https://explorer.iota.org/mainnet/message/3aaac9b55799e649bcceb73639135379fc3bf42a8b43cfece120b6e076c54a69) to add attestation info, referencing the CID key of the original asset. Note that the attestations can come from wallets belonging to other parties.

See above example here: https://authmedia.net/dia-certificate?mid=bafybeia7buylzu37ldtugql2eupy64fw3gzjqyoivgt3jyxe6d4yuggh24

Not all fields are relevant to us, as we are often not registering image content. We'll navigate this with custom UI, but it'll be useful to understand the standard data legend we should populate, or whether the _Data JSON_ can be completely arbitrary:

![Screen Shot 2022-03-01 at 9 49 03 AM](https://user-images.githubusercontent.com/2261308/156190889-7ec1aeb3-797a-4648-894a-5601a83f0dda.png)

As a starting point, let's figure out how we can call Numbers API from Python.

**Comment by makeworld-the-better-one** [comment]
API to register a commit: https://github.com/numbersprotocol/enterprise-service/wiki/Web-3.0-API#nit-commit

**Comment by benhylau** [comment]
@bafu can you comment on what I need to do to prepare these for registration? Right now, you see we have simply submitted CIDs to the `commit` API without any particular schema conformance on `assetTree` or `author`. I want to know whether there are expectations on the Numbers side.

See: https://github.com/starlinglab/integrity-backend/blob/f5d22c62d0774e556760dfa21a705d477d4c4a8d/integritybackend/numbers.py#L43-L46

**Comment by benhylau** [comment]
Using Numbers' new API:

Request:

```
$ curl --location --request POST 'https://node.numbersprotocol.io/version-test/api/1.1/wf/nit_create_asset' \
--header 'Authorization: Bearer [REDACTED]' \
--form 'assetCid="bafybeif3ctgbmiso4oykvwj6jebyrkjxqr26bfrkesla5yr2ypgx47wgle"' \
--form 'assetMimetype="application/octet-stream"' \
--form 'assetTimestampCreated="2022-05-22T09:51:50+00:00"' \
--form 'custom="{\"content1\":{\"sha256\":\"449217b1f3acb0bef5f59baa2a43037cdca19e2ef29f9c8c86a58594f0b6718f\",\"md5\":\"aba7a26c29c8db17442ca4f281573197\"},\"keywords\":\"word1,word2\"}"' \
--form 'nftMetadata="{
    \"name\": \"Ukrainian Soldiers at Saber Guardian 2014\",
    \"description\": \"Ukrainian Soldiers at Saber Guardian 2014 by U.S. Army Europe is marked with CC PDM 1.0.\",
    \"external_url\": \"ipfs://bafybeif3ctgbmiso4oykvwj6jebyrkjxqr26bfrkesla5yr2ypgx47wgle\",
    \"custom\": {\"content1\":{\"sha256\":\"449217b1f3acb0bef5f59baa2a43037cdca19e2ef29f9c8c86a58594f0b6718f\",\"md5\":\"aba7a26c29c8db17442ca4f281573197\"},\"keywords\":\"word1,word2\"}
}
"'
```

Response:
```
{
    "status": "success",
    "response": {
        "txHash": "0x0af44f222866ded5ca7b66a0134b0f77ddabf4992b54bd1fd311fe27814b4e04",
        "assetCid": "bafybeif3ctgbmiso4oykvwj6jebyrkjxqr26bfrkesla5yr2ypgx47wgle",
        "assetTreeCid": "bafkreihvggnxxmxvsdbrspf7zmxo4s3e6in4m3z3c3fnuin6aph3kawhmm"
    }
}
```

Records:
- assetTree: https://bafkreihvggnxxmxvsdbrspf7zmxo4s3e6in4m3z3c3fnuin6aph3kawhmm.ipfs.infura-ipfs.io/
- nftRecord: https://bafkreihnkmzy5p4bsjmfqwehwwazocu5bgemif3m4zjz2zcx3apvuqibha.ipfs.infura-ipfs.io/
- tokenUri: https://bafkreig6pfhgdjcjhwlh5mrjit2r2ket5luy6ir5lt3orscgeqgftpaptm.ipfs.infura-ipfs.io/

**Comment by benhylau** [comment]
Q1: Whether JSONs are stored on somewhere in addition to IPFS
>A1: The JSON data is on Infura storage, and I'm adding more storage sources including Numbers node and web3.storage. The update will not affect the APIs' UX.

Q2: How to specify the author
>A2: Author's data is an Identity. The Identity's information is JSON, and you can put customized data here
