### ISSUE TITLE
Expand FileUtil to hash CIDs and do AES encrypt

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#62]
We currently have [FileUtil](https://github.com/starlinglab/starling-integrity-api/blob/main/starlingcaptureapi/file_util.py) that does helper operations for file manipulation. We need to add two new functionalities here:

1. Hash CIDv1 (same algo that Numbers Protocol uses internally for registration)
2. Encrypt with AES-256-CBC

Alongside functions that enable these operations, such as generating an AES key, etc. It is possible that it's more appropriate to rename (or have another class) called `CryptoUtil` as keygen seems to fall out of "file operations" but I'll leave that open.

Note that internally we use sha256 as an internal addressing scheme, where the "asset" has persistent filename as its [sha256 digest](https://github.com/starlinglab/starling-integrity-api/blob/main/starlingcaptureapi/asset_helper.py#L135). Associated metadata files are also named with the matching asset's sha256. We need to keep this system. (Temporary assets are usually named with a UUID.)

## To Do

- [x] Hash (sha256 and Numbers-compatible CIDv1) - done in #64
- [x] Encrypt (AES for data using collection key) - done in #66 
  - [ ] Pin test asset on IPFS node and make sure our computed CID matches what say... IPFS Desktop does
- [ ] Connect with @anaulin to generate these (see https://github.com/starlinglab/starling-integrity-api/issues/53#issuecomment-1058107379):
    - hash://sha256/9564b85669d5e96ac969dd0161b8475bbced9e5999c6ec598da718a3045d6f2e
    - ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi
    - md5://<md5_hash>

**Comment by makeworld-the-better-one** [comment]
Not sure if MD5 should also be added to this list? Covered in #71

**Comment by benhylau** [comment]
This is done.
