### ISSUE TITLE
Create JS sample for displaying C2PA-injected images created from backend

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#7]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Render overlay from C2PA-injected image using Adobe's js-sdk.  

This needs to support lazy loading of the C2PA image.

Take @YurkoWasHere's b64 lazy load http://node2.e-mesh.net/lazy/index.html and Adobe's js-overlay https://contentauthenticity.org/how-it-works and make it work with an image we created.

<img width="1391" alt="Screen Shot 2021-11-18 at 11 19 02 PM" src="https://user-images.githubusercontent.com/2261308/144249979-9796d300-9b05-4b99-acb3-39aec1eccb99.png">

## To Do

- [x] @benhylau add test image for parsing
- [ ] Parse an image using [this sample code provided by Adobe](https://js-sdk.contentauthenticity.org/docs/getting-started/quick-start/)
- [ ] Pick up the js-overlay code from Adobe on Dec 3 and render with our image
- [ ] Verify b64-encoded parsing
- [ ] Pass to SCMP to verify this works behind Cloudflare
- [ ] Render custom keys (e.g. IPFS CID) on overlay

**Comment by benhylau** [comment]
Let's get this into the repo as an example. Can we take a photo from a url param and make CORS work?
https://lab1.starling.hypha.coop/lab/Sample2/
