### ISSUE TITLE
Adopt new configuration schema and implement new file structure with Collection directories

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#73]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Decide on file structure for Collections.  

File structure chart: https://app.mural.co/t/starlinglab7814/m/starlinglab7814/1645818950661/a7fde68442959d82fbb968f2f825964cc1db86aa?sender=ub3a421c048efd7d270741703

## To Do

- [x] Figure out bot directories
- [x] Figure out WACZ directories

☝🏽 from perspective of the _backend_ (this repo) we have defined the requirements for files to be dropped for processing. Bringing them to the right format to "drop off" will be responsibility of Collector clients.

We also discussed moving HTTP API server (i.e. POST handler) out to become a standalone Collector client. This may spin off to a future issue.

- [x] Any batching of items (edit: done by client as well, not backend)
- [x] How files make their way into `create` folders (see: https://hackmd.io/ALDXEZWjTDeyeoF7cE1AYg?view)
- [x] Implementation https://github.com/starlinglab/starling-integrity-api/issues/73#issuecomment-1071505003

**Comment by benhylau** [comment]
## Bots

| Platform | Scope per Docker instance | Collections per Docker instance | Channels per Collection |
|:--|:--|:--|:--|
| Slack | Workspace | 1 | Many |
| Telegram | Bot Account* | 1** | Many |
| Signal | Phone Number | 1 | Many |

*Can have many Bot Accounts per phone number
**Possible to split into many, but requires content inspection

**Comment by benhylau** [comment]
@anaulin is working on:
- [ ] new configuration schema
- [ ] directory structure and naming/bundling of files
- [ ] update folder watchers

See: https://hackmd.io/ALDXEZWjTDeyeoF7cE1AYg?view

**Comment by anaulin** [comment]
The one remaining piece of work on this is moving the "legacy" actions to use the new system, which is now being tracked in: https://github.com/starlinglab/integrity-backend/issues/79
