### ISSUE TITLE
Update legacy config handling

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/integrity-backend#85]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

`config.py` has been updated with functions to read the config variables easily. All access to configurations should be done via the `config.ORGANIZATION_CONFIG.get*` functions.

There is currently a re-indexing of the read config to a key:value pair that should be addressed as well.

## To Do

- [ ] Identify where indexed config variables are used [details](https://github.com/starlinglab/integrity-backend/blob/patches/integritybackend/config.py#L79-L92)
  - `init_dirs` does not trigger without this so there is something in the startup of the script
- [ ] Pass IDs instead of config fragments to functions
  -  IE:
    - https://github.com/starlinglab/integrity-backend/blob/patches/integritybackend/actions.py#L35
    - https://github.com/starlinglab/integrity-backend/blob/patches/integritybackend/actions.py#L255
    - https://github.com/starlinglab/integrity-backend/blob/patches/integritybackend/actions.py#L275
- [ ] use config `config.ORGANIZATION_CONFIG.get*` functions to access data throughout

**Comment by benhylau** [comment]
See: https://github.com/starlinglab/integrity-backend/pull/84/files#r842150626
