### ISSUE TITLE
Open source the repo

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-backend#9]
## Task Summary

📅 **Due date:** N/A  
🎯 **Success criteria:** Open source the repo.  

This task tracks a list of TODOs for FOSSing.

## To Do

- [x] Change repo name to `starling-integrity-api`
- [x] Add MIT license
- [x] Verify no credentials / sensitive info are in the code and issues
- [x] Make sure it's well documented
- [x] Make this repo public
- [x] Rename subfolder https://github.com/starlinglab/starling-integrity-api/issues/9#issuecomment-1044048045
- [x] Move content from [UA data model pad](https://hackmd.io/ALDXEZWjTDeyeoF7cE1AYg?view) to here @benhylau 
  - Moved out to larger documentation effort

**Comment by anaulin** [comment]
@benhylau Are there any other documentation tasks that need to happen before we can mark this ticket as "done"? If yes, can you clarify what should be further documented, so that I can get it done?

**Comment by benhylau** [comment]
I think we should doc the `create` API. This way, we can have clients other than starling-capture sending to this. I think it's a matter of taking from here: https://github.com/starlinglab/starling-integrity-api/issues/3#issuecomment-978061281 what actually got implemented (e.g. what error codes are actually returned, what multipart keys are actually read, etc.) and putting it in README.md or a API.md.

I think @YurkoWasHere has some ansibles for server provisioning. It may be good to add a sentence linking to that.

**Comment by benhylau** [comment]
Also need to rename the subfolder to `starlingintegrityapi` from `starlingcaptureapi` still.

**Comment by anaulin** [comment]
As per the conversation in https://starlinglabhq.slack.com/archives/C02LDUFLSR2/p1648247634341929, also rename the repo to remove `api` from the name, which is no longer accurate.

**Comment by anaulin** [comment]
@benhylau the one remaining task in this issue is "Move content from [UA data model pad](https://hackmd.io/ALDXEZWjTDeyeoF7cE1AYg?view) to here", so I'm reassigning the ticket for you to complete and close.
